
package com.demo.view;

import com.demo.controlller.ControllerLogin;
import javax.swing.JOptionPane;

public class VistaLogin extends javax.swing.JFrame {

    ControllerLogin cLogin;
    
    public VistaLogin() {
        
        initComponents();
        this.setLocation(400, 200);
        cLogin = new ControllerLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jbtnLogIn = new javax.swing.JButton();
        jbtnLogUp = new javax.swing.JButton();
        jbtnRecuperar = new javax.swing.JButton();
        pwp_clave = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono_b.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, -1));

        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 65, -1));

        jLabel3.setText("CLAVE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        getContentPane().add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 115, -1));

        jbtnLogIn.setText("Log In");
        jbtnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogInActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, -1));

        jbtnLogUp.setText("Log Up");
        jbtnLogUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogUpActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, -1));

        jbtnRecuperar.setText("Recuperar Clave");
        jbtnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRecuperarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        pwp_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwp_claveActionPerformed(evt);
            }
        });
        getContentPane().add(pwp_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 115, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondoL.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 360, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogInActionPerformed
        String usuario, clave;
        usuario = this.jtxtUsuario.getText();
        clave = this.pwp_clave.getText();
        boolean band;
        band = this.cLogin.logIn(usuario, clave);
        if (band) {
            //Login correcto
            JOptionPane.showMessageDialog(this, "Login Correcto");
        }else{
            //login incorrecto
            JOptionPane.showMessageDialog(this, "Login Incorrecto");
        }
    }//GEN-LAST:event_jbtnLogInActionPerformed

    private void jbtnLogUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLogUpActionPerformed

    private void jbtnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRecuperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRecuperarActionPerformed

    private void pwp_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwp_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwp_claveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnLogIn;
    private javax.swing.JButton jbtnLogUp;
    private javax.swing.JButton jbtnRecuperar;
    private javax.swing.JTextField jtxtUsuario;
    private javax.swing.JPasswordField pwp_clave;
    // End of variables declaration//GEN-END:variables
}
